# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [4]:
file = ("../output_data/describe_data.csv")
file_df = pd.read_csv(file)
file_df.head()

,City,Lat,lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Ostrovnoy,68.05,39.51,275.16,83,100,5.69,RU,1603166466
1,Mahébourg,-20.41,57.70,297.15,78,40,5.10,MU,1603166467
2,Qaanaaq,77.48,-69.36,271.60,86,73,4.00,GL,1603166467
3,Zhuhai,22.28,113.57,298.15,69,20,7.20,CN,1603166468
4,Cape Town,-33.93,18.42,287.59,93,75,1.00,ZA,1603166436

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [16]:
gmaps.configure(api_key=g_key)
hum = file_df["Humidity"].astype(float)
hum_max = hum.max()
location = file_df[["Lat", "lng"]]

fig = gmaps.figure(center=(46.0, -5.0), zoom_level=2)

heat_layer = gmaps.heatmap_layer(location, weights = hum, dissipating=False, max_intensity=hum_max, point_radius=3)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [34]:
# A max temperature lower than 80 degrees but higher than 70.
# Wind speed less than 10 mph.
# Zero cloudiness.
# Drop any rows that don't contain all three conditions. You want to be sure the weather is ideal.
# Note: Feel free to adjust to your specifications but be sure to limit the number of rows returned by your API 
# requests to a reasonable number.
new_data = file_df.loc[(file_df["Wind Speed"] <= 10) & (file_df["Cloudiness"] ==0) & (file_df["Max Temp"] >= 150)
                       & (file_df["Max Temp"] >= 176) ]
              
new_data = new_data.dropna(how='any')

new_data.head()

,City,Lat,lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
26,Colonelganj,27.13,81.70,300.41,44,0,1.57,IN,1603166478
28,Rikitea,-23.12,-134.97,296.62,77,0,5.23,PF,1603166479
38,Ayan,56.45,138.17,274.46,72,0,6.13,RU,1603166483
46,Beloha,-25.17,45.05,295.91,49,0,1.50,MG,1603166487
52,Tāybād,34.74,60.78,290.19,23,0,1.56,IR,1603166489

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [36]:
hotel_df = new_data.loc[:,['City', 'Country', 'Lat', 'lng']]

hotel_df['Hotel Name'] = ""

hotel_df.head()

           City Country    Lat     lng Hotel Name
26  Colonelganj      IN  27.13   81.70
28      Rikitea      PF -23.12 -134.97
38         Ayan      RU  56.45  138.17
46       Beloha      MG -25.17   45.05
52       Tāybād      IR  34.74   60.78

In [37]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

params = {"type" : "hotel", 
         'keyword' : 'hotel',
         'radius': 5000,
         'key' : g_key}

In [38]:
for index, row in hotel_df.iterrows():
    lat = row["Lat"]
    lng = row['lng']
    city_name = row['City']
    
    params["location"] = f"{lat},{lng}"
    print(f"Retrieving Results for index {index}:{city_name}.")
    response = requests.get(base_url, params=params).json()
    
    results = response['results']
    
    try:
        print(f"Closest hotel in {city_name} is {results[0]['name']}.")
        hotel_df.loc[index, "Hotel Name"] = results[0]['name']
        
    except (KeyError, IndexError):
        print("Missing filed/result .. skipping.")
        
    print("-------------------------------")
    
print("End")

Retrieving Results for index 26:Colonelganj.
Closest hotel in Colonelganj is Anand Hotel.
-------------------------------
Retrieving Results for index 28:Rikitea.
Closest hotel in Rikitea is Pension Maro'i.
-------------------------------
Retrieving Results for index 38:Ayan.
Closest hotel in Ayan is Gostinitsa.
-------------------------------
Retrieving Results for index 46:Beloha.
Missing filed/result .. skipping.
-------------------------------
Retrieving Results for index 52:Tāybād.
Closest hotel in Tāybād is دفتردستک محمدسیاه.
-------------------------------
Retrieving Results for index 56:Pisco.
Closest hotel in Pisco is Embassy Beach.
-------------------------------
Retrieving Results for index 58:Hofn.
Closest hotel in Hofn is Hótel Höfn.
-------------------------------
Retrieving Results for index 74:Hobyo.
Closest hotel in Hobyo is Osmani Hotel.
-------------------------------
Retrieving Results for index 77:Khor.
Missing filed/result .. skipping.
-------------------------------
Retrieving Results for index 78:Crotone.
Closest hotel in Crotone is Arìa Residenze d'aMare.
-------------------------------
Retrieving Results for index 83:Araouane.
Missing filed/result .. skipping.
-------------------------------
Retrieving Results for index 94:Najrān.
Missing filed/result .. skipping.
-------------------------------
Retrieving Results for index 122:Forio.
Closest hotel in Forio is Hotel Villa Tre Sorelle.
-------------------------------
Retrieving Results for index 123:Ruska Poliana.
Closest hotel in Ruska Poliana is Vershnyk.
-------------------------------
Retrieving Results for index 133:Adrar.
Missing filed/result .. skipping.
-------------------------------
Retrieving Results for index 138:Morondava.
Closest hotel in Morondava is Palissandre Cote Ouest resort & SPA.
-------------------------------
Retrieving Results for index 141:Sanchazi.
Closest hotel in Sanchazi is Sengong Hotel.
-------------------------------
Retrieving Results for index 145:Comodoro Rivadavia.
Closest hotel in Comodoro Rivadavia is Austral Hotel.
-------------------------------
Retrieving Results for index 148:Ibrā’.
Closest hotel in Ibrā’ is تفضل بيت ضيافة Geust house tafadal.
-------------------------------
Retrieving Results for index 160:Province of Trapani.
Missing filed/result .. skipping.
-------------------------------
Retrieving Results for index 172:Antsohihy.
Closest hotel in Antsohihy is Hôtel le Paradisier.
-------------------------------
Retrieving Results for index 178:Faya.
Missing filed/result .. skipping.
-------------------------------
Retrieving Results for index 187:Mackay.
Closest hotel in Mackay is Oaks Mackay Rivermarque Hotel.
-------------------------------
Retrieving Results for index 192:Port Hedland.
Closest hotel in Port Hedland is The Esplanade Hotel.
-------------------------------
Retrieving Results for index 197:Coquimbo.
Closest hotel in Coquimbo is Hotel Boutique Costa Del Sol.
-------------------------------
Retrieving Results for index 227:Tabas.
Closest hotel in Tabas is Amir hotel.
-------------------------------
Retrieving Results for index 244:Pasni.
Closest hotel in Pasni is Juddi Hotel.
-------------------------------
Retrieving Results for index 259:Kumul.
Closest hotel in Kumul is 哈密环球大酒店.
-------------------------------
Retrieving Results for index 260:Pahrump.
Closest hotel in Pahrump is Pahrump Nugget.
-------------------------------
Retrieving Results for index 264:Saint-Leu.
Closest hotel in Saint-Leu is Iloha Seaview Hotel.
-------------------------------
Retrieving Results for index 288:San Quintín.
Closest hotel in San Quintín is Old Mill Hotel.
-------------------------------
Retrieving Results for index 296:Khāsh.
Closest hotel in Khāsh is خوابگاه دانشجویی خاش.
-------------------------------
Retrieving Results for index 299:Jiuquan.
Closest hotel in Jiuquan is Jiuquan Hotel.
-------------------------------
Retrieving Results for index 300:Betafo.
Missing filed/result .. skipping.
-------------------------------
Retrieving Results for index 308:Nioro.
Missing filed/result .. skipping.
-------------------------------
Retrieving Results for index 310:Airai.
Missing filed/result .. skipping.
-------------------------------
Retrieving Results for index 311:Balkanabat.
Closest hotel in Balkanabat is Nebitchi Hotel.
-------------------------------
Retrieving Results for index 321:Mandera.
Closest hotel in Mandera is Granada hotel Mandera.
-------------------------------
Retrieving Results for index 325:Edd.
Missing filed/result .. skipping.
-------------------------------
Retrieving Results for index 330:Biltine.
Closest hotel in Biltine is Hôtel Trois Étoiles de Biltine.
-------------------------------
Retrieving Results for index 346:Chiredzi.
Closest hotel in Chiredzi is The Nesbitt Arms.
-------------------------------
Retrieving Results for index 350:Yangi Marg`ilon.
Closest hotel in Yangi Marg`ilon is ATLAS HOTEL.
-------------------------------
Retrieving Results for index 356:Leh.
Closest hotel in Leh is TSOKAR Retreat.
-------------------------------
Retrieving Results for index 358:Alyangula.
Closest hotel in Alyangula is Groote Eylandt Lodge.
-------------------------------
Retrieving Results for index 367:Pampierstad.
Missing filed/result .. skipping.
-------------------------------
Retrieving Results for index 370:Sfântu Gheorghe.
Closest hotel in Sfântu Gheorghe is Hotel Castel.
-------------------------------
Retrieving Results for index 385:Santa Maria.
Closest hotel in Santa Maria is Itaimbé Palace Hotel.
-------------------------------
Retrieving Results for index 404:Manama.
Closest hotel in Manama is Four Seasons Hotel Bahrain Bay.
-------------------------------
Retrieving Results for index 414:Kalat.
Closest hotel in Kalat is Balochistan Hotel.
-------------------------------
Retrieving Results for index 416:Kirkuk.
Closest hotel in Kirkuk is Hotel snubal.
-------------------------------
Retrieving Results for index 434:Hong Kong.
Closest hotel in Hong Kong is W Hong Kong.
-------------------------------
Retrieving Results for index 436:Zaysan.
Closest hotel in Zaysan is Zaysan Hotel.
-------------------------------
Retrieving Results for index 443:Lucapa.
Missing filed/result .. skipping.
-------------------------------
Retrieving Results for index 444:Birjand.
Closest hotel in Birjand is هتل پرويز.
-------------------------------
Retrieving Results for index 448:Doha.
Closest hotel in Doha is Al Najada Doha Hotel by Tivoli.
-------------------------------
Retrieving Results for index 464:Atasū.
Missing filed/result .. skipping.
-------------------------------
Retrieving Results for index 479:Zhezkazgan.
Closest hotel in Zhezkazgan is Hotel Zumrat.
-------------------------------
Retrieving Results for index 483:Necochea.
Closest hotel in Necochea is Complejo Villa Don Cata.
-------------------------------
Retrieving Results for index 510:Atar.
Closest hotel in Atar is Odar kanawal.
-------------------------------
Retrieving Results for index 515:Madaoua.
Missing filed/result .. skipping.
-------------------------------
Retrieving Results for index 525:Makkah al Mukarramah.
Closest hotel in Makkah al Mukarramah is Elaf Al Salam Hotel.
-------------------------------
Retrieving Results for index 526:Viedma.
Closest hotel in Viedma is Hotel Austral Viedma.
-------------------------------
Retrieving Results for index 532:Burns Lake.
Closest hotel in Burns Lake is Key-oh Lodge.
-------------------------------
Retrieving Results for index 534:Marzuq.
Missing filed/result .. skipping.
-------------------------------
Retrieving Results for index 537:Matam.
Closest hotel in Matam is Pres De Auberge Djiby Ba.
-------------------------------
End

In [44]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "lng"]]

In [45]:
markers = gmaps.marker_layer(locations, info_box_content = hotel_info)

fig.add_layer(markers)

fig

Figure(layout=FigureLayout(height='420px'))